"""is active status added to interim wallet

Revision ID: 11d638f24e1b
Revises: 0ddb5a0ac37b
Create Date: 2025-02-02 01:52:34.645385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11d638f24e1b'
down_revision: Union[str, None] = '0ddb5a0ac37b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interimwallet', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interimwallet', 'is_active')
    # ### end Alembic commands ###
