"""Entitlement relation created for subscription

Revision ID: d0872829ac13
Revises: 9f164e399434
Create Date: 2025-03-11 06:12:17.193990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0872829ac13'
down_revision: Union[str, None] = '9f164e399434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_entitlement',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entitlement_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entitlement_id'], ['entitlement.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'entitlement_id')
    )
    op.add_column('entitlement', sa.Column('cost', sa.Float(), nullable=False))
    op.drop_constraint('entitlement_user_id_fkey', 'entitlement', type_='foreignkey')
    op.drop_column('entitlement', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entitlement', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('entitlement_user_id_fkey', 'entitlement', 'users', ['user_id'], ['id'])
    op.drop_column('entitlement', 'cost')
    op.drop_table('user_entitlement')
    # ### end Alembic commands ###
